# Generated by Django 4.1 on 2022-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maritimeaccidents", name="location_of_incident",
        ),
        migrations.RemoveField(model_name="piracy", name="location_of_incident",),
        migrations.RemoveField(model_name="shiptoship", name="location_of_incident",),
        migrations.AddField(
            model_name="drugtrafficking",
            name="incident_details",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="drugtrafficking",
            name="sub_region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EEZ", "EEZ"),
                    ("Territorial waters", "Territorial waters"),
                    ("Ports/Anchorage", "Ports/Anchorage"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="iuu",
            name="incident_details",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="iuu",
            name="sub_region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EEZ", "EEZ"),
                    ("Territorial waters", "Territorial waters"),
                    ("Ports/Anchorage", "Ports/Anchorage"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="maritimeaccidents",
            name="incident_details",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="maritimeaccidents",
            name="multiple_vessels_involved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maritimeaccidents",
            name="sub_region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EEZ", "EEZ"),
                    ("Territorial waters", "Territorial waters"),
                    ("Ports/Anchorage", "Ports/Anchorage"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="maritimeaccidents",
            name="vessel_involved",
            field=models.CharField(
                blank=True, help_text="Enter MMSI for vessel", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="piracy",
            name="incident_details",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="piracy",
            name="sub_region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EEZ", "EEZ"),
                    ("Territorial waters", "Territorial waters"),
                    ("Ports/Anchorage", "Ports/Anchorage"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shiptoship",
            name="incident_details",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="shiptoship",
            name="sub_region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EEZ", "EEZ"),
                    ("Territorial waters", "Territorial waters"),
                    ("Ports/Anchorage", "Ports/Anchorage"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stowaway",
            name="incident_details",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="stowaway",
            name="sub_region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EEZ", "EEZ"),
                    ("Territorial waters", "Territorial waters"),
                    ("Ports/Anchorage", "Ports/Anchorage"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
