# Generated by Django 4.1 on 2022-08-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_remove_maritimeaccidents_location_of_incident_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piracy",
            name="location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piracy",
            name="location_lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
