# Generated by Django 4.1 on 2022-09-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_alter_piracy_location_lat_alter_piracy_location_lon"),
    ]

    operations = [
        migrations.RenameModel(old_name="StowAway", new_name="IllegalMigrations",),
    ]
